-- Actividad de usuarios
WITH
	UA AS (
		SELECT
			U.ID_USUARIO,
			U.NOMBRE_USUARIO,
			COUNT(DISTINCT R.ID_RUN) AS RUNS_TOTALES,
			COUNT(*) FILTER (
				WHERE
					R.ESTADO = 'COMPLETED'
			) AS RUNS_OK,
			COUNT(*) FILTER (
				WHERE
					R.ESTADO IS NOT NULL
					AND R.ESTADO <> 'COMPLETED'
			) AS RUNS_NO_OK,
			MAX(R.TIEMPO_INICIO) AS ULTIMO_RUN
		FROM
			"Usuario" U
			LEFT JOIN "Run" R ON R.ID_USUARIO = U.ID_USUARIO
		GROUP BY
			U.ID_USUARIO,
			U.NOMBRE_USUARIO
	)
SELECT
	ID_USUARIO,
	NOMBRE_USUARIO,
	RUNS_TOTALES,
	RUNS_OK,
	RUNS_NO_OK,
	ROUND(100.0 * RUNS_OK / NULLIF(RUNS_TOTALES, 0), 2) AS PCT_OK,
	ULTIMO_RUN
FROM
	UA
ORDER BY
	PCT_OK DESC
LIMIT 10;