-- Información de Runs completados ordenados por los más rápidos
SELECT
	R.ID_RUN,
	R.NUMERO_RUN,
	R.ESTADO,
	R.TIEMPO_INICIO,
	R.TIEMPO_FIN,
	EXTRACT(
		EPOCH
		FROM
			(R.TIEMPO_FIN - R.TIEMPO_INICIO)
	) AS DURACION_S,
	E.NOMBRE_EXPERIMENTO,
	M.ALGORITMO
FROM
	"Run" R
	JOIN "Experimento" E ON E.ID_EXPERIMENTO = R.ID_EXPERIMENTO
	LEFT JOIN "Modelo" M ON M.ID_RUN = R.ID_RUN
WHERE
	R.ESTADO = 'COMPLETED'
	AND R.TIEMPO_INICIO IS NOT NULL
	AND R.TIEMPO_FIN IS NOT NULL
ORDER BY
	DURACION_S ASC
LIMIT 10;