-- Mostrar experimentos con información del proyecto y usuario responsable
SELECT
	P.ID_PROYECTO,
	P.NOMBRE_PROYECTO,
	U.NOMBRE_USUARIO AS LIDER_PROYECTO,
	COUNT(DISTINCT E.ID_EXPERIMENTO) AS N_EXPERIMENTOS,
	COUNT(DISTINCT R.ID_RUN) AS N_RUNS
FROM
	"Proyecto" P
	LEFT JOIN "Experimento" E ON E.ID_PROYECTO = P.ID_PROYECTO
	LEFT JOIN "Run" R ON R.ID_EXPERIMENTO = E.ID_EXPERIMENTO
	JOIN "ParticipacionEnProyecto" PP ON P.ID_PROYECTO = PP.ID_PROYECTO
	JOIN "Usuario" U ON PP.ID_USUARIO = U.ID_USUARIO
WHERE
	PP.ROL = 'Líder de Proyecto'
	AND PP.FECHA_BAJA IS NULL
GROUP BY
	P.ID_PROYECTO,
	P.NOMBRE_PROYECTO,
	U.NOMBRE_USUARIO
ORDER BY
	N_RUNS DESC,
	N_EXPERIMENTOS DESC
LIMIT 10;