-- Información de los Runs
SELECT
	P.NOMBRE_PROYECTO,
	E.NOMBRE_EXPERIMENTO,
	R.ID_RUN,
	R.NUMERO_RUN,
	R.ESTADO,
	M.FRAMEWORK,
	M.ALGORITMO,
	M.STAGE,
	D.NOMBRE_DATASET,
	DV.VERSION_DATASET
FROM
	"Run" R
	JOIN "Experimento" E ON E.ID_EXPERIMENTO = R.ID_EXPERIMENTO
	JOIN "Proyecto" P ON P.ID_PROYECTO = E.ID_PROYECTO
	LEFT JOIN "Modelo" M ON M.ID_RUN = R.ID_RUN
	LEFT JOIN "Dataset" D ON D.ID_DATASET = R.ID_DATASET
	LEFT JOIN "DatasetVersion" DV ON DV.ID_DATASET = R.ID_DATASET
	AND DV.VERSION_DATASET = R.VERSION_DATASET
ORDER BY
	P.NOMBRE_PROYECTO,
	E.NOMBRE_EXPERIMENTO,
	R.NUMERO_RUN
LIMIT 10;