-- Hiperparámetros más utilizados por algoritmo
SELECT
	M.ALGORITMO,
	H.NOMBRE_HP,
	COUNT(H.ID_RUN) AS RUNS_CON_HP
FROM
	"Hiperparametro" H
	JOIN "Run" R ON R.ID_RUN = H.ID_RUN
	JOIN "Modelo" M ON M.ID_RUN = R.ID_RUN
WHERE
	R.ESTADO = 'COMPLETED'
	AND M.ALGORITMO IS NOT NULL
GROUP BY
	M.ALGORITMO,
	H.NOMBRE_HP
ORDER BY
	M.ALGORITMO,
	RUNS_CON_HP DESC
LIMIT 10;