-- Mejores hiperparámetros por algoritmo, métrica y split
WITH
	PERF AS (
		SELECT
			M.ALGORITMO,
			H.NOMBRE_HP,
			H.VALOR_JSON,
			MT.NOMBRE_METRICA,
			MT.SPLIT,
			AVG(MT.VALOR) AS AVG_METRIC
		FROM
			"Modelo" M
			JOIN "Run" R ON R.ID_RUN = M.ID_RUN
			JOIN "Hiperparametro" H ON H.ID_RUN = R.ID_RUN
			JOIN "Metrica" MT ON MT.ID_RUN = R.ID_RUN
		WHERE
			R.ESTADO = 'COMPLETED'
			AND M.ALGORITMO IS NOT NULL
		GROUP BY
			M.ALGORITMO,
			H.NOMBRE_HP,
			H.VALOR_JSON,
			MT.NOMBRE_METRICA,
			MT.SPLIT
	),
	RANKED AS (
		SELECT
			*,
			ROW_NUMBER() OVER (
				PARTITION BY
					ALGORITMO,
					NOMBRE_METRICA,
					SPLIT,
					NOMBRE_HP
				ORDER BY
					CASE
						WHEN LOWER(NOMBRE_METRICA) IN ('loss', 'rmse', 'mae', 'mse', 'log_loss') THEN AVG_METRIC
						ELSE - AVG_METRIC
					END ASC
			) AS RN
		FROM
			PERF
	)
SELECT
	ALGORITMO,
	NOMBRE_METRICA,
	SPLIT,
	NOMBRE_HP,
	VALOR_JSON,
	ROUND(AVG_METRIC::NUMERIC, 4) AS AVG_METRIC
FROM
	RANKED
WHERE
	RN = 1
ORDER BY
	ALGORITMO,
	NOMBRE_METRICA,
	SPLIT,
	AVG_METRIC
LIMIT 10;