-- Promedio de métricas por experimento y split
SELECT
	E.NOMBRE_EXPERIMENTO,
	MT.NOMBRE_METRICA,
	MT.SPLIT,
	ROUND(AVG(MT.VALOR)::NUMERIC, 4) AS MEAN_VAL,
	ROUND(STDDEV(MT.VALOR)::NUMERIC, 4) AS STD_VAL,
	COUNT(*) AS NUM_RUNS
FROM
	"Metrica" MT
	JOIN "Run" R ON R.ID_RUN = MT.ID_RUN
	JOIN "Experimento" E ON E.ID_EXPERIMENTO = R.ID_EXPERIMENTO
GROUP BY
	E.NOMBRE_EXPERIMENTO,
	MT.NOMBRE_METRICA,
	MT.SPLIT
HAVING
	COUNT(*) >= 2
ORDER BY
	E.NOMBRE_EXPERIMENTO,
	SPLIT,
	NUM_RUNS DESC
LIMIT 10;